[workspace]
members = ["src/gicv3", "src/libkrun", "src/kruntest", "src/counter", "src/counter-proc"]
resolver = "2"
#panic = "abort"

[profile.release]
#panic = "abort"
lto = true
strip = true

[profile.release-with-debug]
inherits = "release"
lto = "thin"
debug = true
