[global]
excludes = [ "exp/*", "rootfs/utils/fuse/vendor/*", "virtue/*", "vendor/*" ]

[formatter.go]
command = "gofmt"
options = [ "-w" ]
includes = [ "*.go" ]

[formatter.swift]
command = "swift-format"
options = [ "-i" ]
includes = [ "*.swift" ]

[formatter.rust]
command = "rustfmt"
options = [ "--edition", "2021" ]
includes = [ "*.rs" ]

[formatter.c]
command = "clang-format"
options = [ "-i" ]
includes = [ "*.c", "*.h", "*.cpp", "*.hpp" ]

[formatter.python]
command = "black"
includes = [ "*.py" ]
