#!/bin/sh

#
# Copyright 2023 Orbital Labs, LLC. All rights reserved.
# 
# Unauthorized copying of this software and associated documentation files (the "Software"), via any medium, is strictly prohibited. Confidential and proprietary.
# 
# The above copyright notice shall be included in all copies or substantial portions of the Software.
#

set -euo pipefail

# mount and set opts first to avoid EBUSY
echo -n 3600 > /proc/fs/nfsd/nfsv4leasetime
echo -n 1 > /proc/fs/nfsd/nfsv4gracetime

#--debug
/opt/pkg/rpc.nfsd 32 --no-udp --no-nfs-version 3 --debug
# -v
/opt/pkg/exportfs -r -v

# still needed for nfs4
#--debug all
/opt/pkg/rpc.mountd --no-udp --no-nfs-version 2 --no-nfs-version 3 --debug all --foreground &
# will cause nfs freeze if it exits
echo -n -950 > /proc/$!/oom_score_adj

/opt/orb/vsocknfs > /proc/fs/nfsd/portlist
