#!/usr/bin/env bash

#
# Copyright 2023 Danny Lin <danny@kdrag0n.dev>. All rights reserved.
# 
# Unauthorized copying of this software and associated documentation files (the "Software"), via any medium, is strictly prohibited. Confidential and proprietary.
# 
# The above copyright notice shall be included in all copies or substantial portions of the Software.
#

set -euo pipefail

echo "[BEGIN] vinit-late"

sysctl -qp /etc/sysctl.conf

# swap
(
    # zram = 1x ram
    zram_mib=$(( $(cat /proc/meminfo | grep MemTotal | awk '{print $2}') / 1024 ))
    echo /dev/vdc1 > /sys/block/zram0/backing_dev
    echo "${zram_mib}M" > /sys/block/zram0/disksize
    echo huge_idle > /sys/block/zram0/writeback
    mkswap /dev/zram0
    swapon -d -p 32767 /dev/zram0
  
    # 1 gib emergency disk swap
    swapon -d -p 1 /dev/vdc2
) &
echo 1000 > /sys/kernel/mm/lru_gen/min_ttl_ms

# guest tools
mkdir -p /data/guest-state/bin/cmdlinks
chmod 777 /data/guest-state/bin/cmdlinks
mount --bind /data/guest-state /opt/orbstack-guest/data

#
#

# nfs root setup
# mount name is visible in machines bind mount
mount -t tmpfs machines -o noatime,mode=700 /nfsroot-rw
cp /opt/orb/nfs-readme.txt /nfsroot-rw/README.txt
# try to reduce nfs cpu usage
touch /nfsroot-rw/.metadata_never_index /nfsroot-rw/.metadata-never-index /nfsroot-rw/.metadata_never_index_unless_rootfs
# bind ro
mount --bind -o ro /nfsroot-rw /nfsroot-ro
# debug only
if [[ -f /opt/orb/is_debug ]]; then
  # root home
  mkdir -p /data/dev-root-home/.ssh
  cp -af /root/.ssh/authorized_keys /data/dev-root-home/.ssh
  mount --bind /data/dev-root-home /root
fi
# for scon bind mounts
mount --make-rshared /nfsroot-ro

# scon prereqs
mount -t tracefs -o rw,nosuid,nodev,noexec,relatime tracefs /sys/kernel/tracing

# oom scores for critical host services that aren't supervised
echo -n -950 > /proc/$(pidof -s chronyd)/oom_score_adj
echo -n -950 > /proc/$(pidof -s udevd)/oom_score_adj

# scon! (pass cmdline args for console)
/opt/orb/scon mgr $(cat /proc/cmdline) &
echo -n -950 > /proc/$!/oom_score_adj

echo "[END] vinit-late"
