#!/usr/bin/env bash

#
# Copyright 2023 Danny Lin <danny@kdrag0n.dev>. All rights reserved.
# 
# Unauthorized copying of this software and associated documentation files (the "Software"), via any medium, is strictly prohibited. Confidential and proprietary.
# 
# The above copyright notice shall be included in all copies or substantial portions of the Software.
#

set -euo pipefail

# mount and set opts first to avoid EBUSY
mount -t nfsd -o nodev,noexec,nosuid nfsd /proc/fs/nfsd
echo -n 30 > /proc/fs/nfsd/nfsv4leasetime
echo -n 1 > /proc/fs/nfsd/nfsv4gracetime

#--debug
/opt/pkg/rpc.nfsd 32 --no-udp --no-nfs-version 3
# -v
/opt/pkg/exportfs -r

# still needed for nfs4
#--debug all
/opt/pkg/rpc.mountd --no-udp --no-nfs-version 2 --no-nfs-version 3

/opt/orb/vsocknfs > /proc/fs/nfsd/portlist
