[package]
name = "vtest"
version = "1.8.1"
authors = ["Sergio Lopez <slp@redhat.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.98"
libvirtue = { path = "../libvirtue" }
libc = "0.2.172"
tracing-subscriber = "0.3.19"
