FROM alpine:edge as base
RUN apk add --no-cache htop
RUN echo 10
COPY Dockerfile /Dockerfile
RUN echo
COPY Dockerfile /Dockerfile2
RUN echo
COPY Dockerfile /Dockerfile3
RUN echo
COPY Dockerfile /Dockerfile4
RUN echo
COPY Dockerfile /Dockerfile5
RUN echo
COPY Dockerfile /Dockerfile6
RUN echo
COPY Dockerfile /Dockerfile7
RUN echo
COPY Dockerfile /Dockerfile8
RUN echo
COPY Dockerfile /Dockerfile9
RUN echo
COPY Dockerfile /Dockerfile10
RUN echo

COPY Dockerfile /Dockerfile
RUN echo
COPY Dockerfile /Dockerfile2
RUN echo
COPY Dockerfile /Dockerfile3
RUN echo
COPY Dockerfile /Dockerfile4
RUN echo
COPY Dockerfile /Dockerfile5
RUN echo
COPY Dockerfile /Dockerfile6
RUN echo
COPY Dockerfile /Dockerfile7
RUN echo
COPY Dockerfile /Dockerfile8
RUN echo
COPY Dockerfile /Dockerfile9
RUN echo
COPY Dockerfile /Dockerfile10
RUN echo
