#!/usr/bin/env bash

#
# Copyright 2022-2023 Danny Lin <danny@kdrag0n.dev>. All rights reserved.
# 
# Unauthorized copying of this software and associated documentation files (the "Software"), via any medium, is strictly prohibited. Confidential and proprietary.
# 
# The above copyright notice shall be included in all copies or substantial portions of the Software.
#

set -uo pipefail
set -e

echo "[BEGIN] vinit-late"

sysctl -qp /etc/sysctl.conf

# swap
(
    # zram = 2x ram
    zram_mib=$(( $(cat /proc/meminfo | grep MemTotal | awk '{print $2}') / 1024 * 2 ))
    echo /dev/vdc1 > /sys/block/zram0/backing_dev
    echo "${zram_mib}M" > /sys/block/zram0/disksize
    echo huge_idle > /sys/block/zram0/writeback
    mkswap /dev/zram0
    swapon -d -p 32767 /dev/zram0
    sysctl vm.swappiness=100 vm.page-cluster=1
  
    # 1 gib emergency disk swap
    swapon -d -p 1 /dev/vdc2
) &
# 2 mib page reporting
echo 9 > /sys/module/page_reporting/parameters/page_reporting_order

# guest tools
mount --bind /data/guest-state /opt/orbstack-guest/data
mount --rbind -o ro /opt/orbstack-guest /mnt/guest-tools

# Listeners for ssh-agent socket
mkdir -p /tmp/launchd-ssh-agent-listeners
touch /tmp/launchd-ssh-agent-listeners/Listeners
mount --bind -o ro /opt/orbstack-guest/run/host-ssh-agent.sock /tmp/launchd-ssh-agent-listeners/Listeners

# setup docker rootfs
#

pushd /opt/docker-rootfs
# binds
mkdir -p /data/docker
mount --bind /data/docker var/lib/docker
popd

#
#

# nfs root setup
mount -t tmpfs tmpfs -o noatime /nfsroot-rw
# try to reduce nfs cpu usage
touch /nfsroot-rw/.metadata_never_index /nfsroot-rw/.metadata-never-index /nfsroot-rw/.metadata_never_index_unless_rootfs
# bind ro
mount --bind -o ro /nfsroot-rw /nfsroot-ro
# debug only
if [[ -f /opt/vc/is_debug ]]; then
  mkdir /nfsroot-rw/data
  mount --bind /data /nfsroot-ro/data
fi

# scon!
/opt/vc/scon &

# resize fs
#xfs_growfs /dev/vdb1
#btrfs filesystem resize max /data

# ok to update quota/balloon now
mkdir -p /tmp/flags
touch /tmp/flags/data_resized
sync -f /data

# late nfs start
rc-service nfs start
# vsock
/opt/vc/add-nfsd-vsock > /proc/fs/nfsd/portlist

echo "[END] vinit-late"
