#!/usr/bin/env bash

#
# Copyright 2022-2023 Danny Lin <danny@kdrag0n.dev>. All rights reserved.
# 
# Unauthorized copying of this software and associated documentation files (the "Software"), via any medium, is strictly prohibited. Confidential and proprietary.
# 
# The above copyright notice shall be included in all copies or substantial portions of the Software.
#

set -uo pipefail

echo "[BEGIN] vinit-early"

# net
echo 0 > /proc/sys/net/ipv6/conf/eth0/accept_ra
echo 0 > /proc/sys/net/ipv6/conf/eth0/accept_dad # fix tentative ipv6 delay
ip link set eth0 up
ip addr add 172.30.30.2/24 dev eth0
ip route add default via 172.30.30.1 dev eth0
ip addr add fc00:96dc:7096:1d21::2/64 dev eth0
ip route add default via fc00:96dc:7096:1d21::1 dev eth0

# control server
# must be after net for IP
ip link set lo up # too early
vcontrol_token=$(cat /proc/cmdline | sed 's/ /\n/g' | grep vc.vcontrol_token= | sed 's/vc.vcontrol_token=//g') || true
/opt/vc/vcontrol "$vcontrol_token" &

# early disk perf
echo none > /sys/block/vda/queue/scheduler
echo none > /sys/block/vdb/queue/scheduler
echo none > /sys/block/vdc/queue/scheduler

# resize data
# parse vc.data_size=10240 from /proc/cmdline
data_size=$(cat /proc/cmdline | sed 's/ /\n/g' | grep vc.data_size= | sed 's/vc.data_size=//g') || true
if [[ -n "$data_size" ]]; then
    # get existing size
    old_size_bytes=$(blockdev --getsize64 /dev/vdb1)
    old_size=$((old_size_bytes / 1024 / 1024))
    # for safety, only allow increasing size
    if [[ "$old_size" -lt "$data_size" ]]; then
        echo "resize data to $data_size"
        echo ",${data_size}M" | sfdisk --force /dev/vdb
        # FS must be resized in vinit-late
        # XFS can only be resized online
    elif [[ "$old_size" -gt "$data_size" ]]; then
        echo "attempt to reduce data size: $data_size"
    fi
fi

#resize.f2fs /dev/vdb1
#fsck.ext4 -y /dev/vdb1
#resize2fs /dev/vdb1
#btrfs filesystem resize max /data

# virtiofs share
mount -t virtiofs mac /mnt/mac

# rosetta
mount -t virtiofs rosetta /mnt/rosetta
mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
echo ':rosetta:M:0:\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x3e\x00:\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/mnt/rosetta/rosetta:CF' > /proc/sys/fs/binfmt_misc/register

# host service proxies
socat UNIX-LISTEN:/opt/orbstack-guest/run/hostssh.sock,fork,reuseaddr,mode=600 TCP:172.30.30.201:22,nodelay &
socat UNIX-LISTEN:/opt/orbstack-guest/run/host-ssh-agent.sock,fork,reuseaddr,mode=600 TCP:172.30.30.201:23,nodelay &
socat UNIX-LISTEN:/opt/orbstack-guest/run/hcontrol.sock,fork,reuseaddr,mode=600 TCP:172.30.30.201:8300,nodelay &

echo "[END] vinit-early"
