# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];

  users.users.{{.Username}} = {
    isNormalUser = true;{{if .Password}}
    hashedPassword = "{{.Password}}";{{end}}
    extraGroups = [ "wheel" ];
  };{{if .NoPassword}}

  security.sudo.wheelNeedsPassword = false;{{end}}{{if .Password}}

  users.users.root.hashedPassword = "{{.Password}}";{{end}}

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "{{.Timezone}}";

  networking = {
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig.RequiredForOnline = "routable";
    };
  };{{if .Certificates}}

  # Extra certificates from OrbStack.
  security.pki.certificates = [
    ''
      {{.Certificates}}
    ''
  ];{{end}}

  system.stateVersion = "{{.StateVersion}}"; # Did you read the comment?
}
