[package]
name = "vmm"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[features]
default = ["net", "blk"]
tee = []
amd-sev = [
    "blk",
    "tee",
    "codicon",
    "kbs-types",
    "procfs",
    "serde",
    "serde_json",
    "sev",
    "curl",
]
net = []
blk = []
efi = ["blk", "net"]
gpu = []

[dependencies]
crossbeam-channel = "0.5"
libc = ">=0.2.39"
tracing = { version = "0.1.41", features = ["release_max_level_info"] }
mio = { version = "1.0.4", features = ["os-poll"] }

arch = { path = "../arch" }
devices = { path = "../devices" }
kernel = { path = "../kernel" }
utils = { path = "../utils" }

# Dependencies for amd-sev
codicon = { version = "3.0.0", optional = true }
kbs-types = { version = "0.5.1, < 0.5.3", features = [
    "tee-sev",
    "tee-snp",
], optional = true }
procfs = { version = "0.17", optional = true }
serde = { version = "1.0.219", optional = true }
serde_json = { version = "1.0.140", optional = true }
sev = { version = "6.2.1", features = ["openssl"], optional = true }
curl = { version = "0.4", optional = true }
nix = "0.24.3"
scopeguard = "1.2.0"
anyhow = "1.0.98"
thiserror = "2.0.12"
gruel = { version = "0.1.0", path = "../gruel" }
vmm-ids = { version = "0.1.0", path = "../vmm-ids" }
hvf = { path = "../hvf" }
crossbeam = "0.8.4"
sysx = { version = "0.1.0", path = "../sysx" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
# cpuid = { path = "../cpuid" }

[target.'cfg(target_os = "linux")'.dependencies]
kvm-bindings = { version = ">=0.6", features = ["fam-wrappers"] }
kvm-ioctls = ">=0.15"

[target.'cfg(target_os = "macos")'.dependencies]
hvf = { path = "../hvf" }

[dev-dependencies]
vmm-sys-util = ">=0.11"
