[package]
name = "gicv3"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.2"
bytemuck = "1.14.3"
derive-where = "1.2.7"
tracing = { version = "0.1.40", features = ["release_max_level_info"] }
num = "0.4.1"
rustc-hash = "1.1.0"
utils = { version = "0.1.0", path = "../utils" }
