[package]
name = "gicv3"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.4.2"
bytemuck = "1.14.3"
derive-where = "1.2.7"
log = "0.4.21"
num = "0.4.1"
rustc-hash = "1.1.0"

hvf = { path = "../hvf" }
