[package]
name = "starry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
libc = "0.2.159"
nix = { version = "0.29.0", features = ["fs", "uio", "zerocopy", "dir", "ioctl"] }
tar = "0.4.42"
zstd = { version = "0.13.2", features = ["zstdmt"] }

[profile.release]
debug = true
