[package]
name = "starry"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.89", features = ["backtrace"] }
tar = "0.4.42"
zstd = { version = "0.13.2", features = ["zstdmt"] }
