[package]
name = "utils"
version = "0.1.0"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[dependencies]
bitflags = "1.2.0"
env_logger = "0.9.0"
libc = ">=0.2.85"
log = { version = "0.4.0", features = ["release_max_level_info"] }
vmm-sys-util = ">=0.11"
