// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: wormhole.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WormholeService_SendCommand_FullMethodName = "/wormhole.WormholeService/SendCommand"
)

// WormholeServiceClient is the client API for WormholeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WormholeServiceClient interface {
	SendCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InputMessage, OutputMessage], error)
}

type wormholeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWormholeServiceClient(cc grpc.ClientConnInterface) WormholeServiceClient {
	return &wormholeServiceClient{cc}
}

func (c *wormholeServiceClient) SendCommand(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[InputMessage, OutputMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WormholeService_ServiceDesc.Streams[0], WormholeService_SendCommand_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[InputMessage, OutputMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WormholeService_SendCommandClient = grpc.BidiStreamingClient[InputMessage, OutputMessage]

// WormholeServiceServer is the server API for WormholeService service.
// All implementations must embed UnimplementedWormholeServiceServer
// for forward compatibility.
type WormholeServiceServer interface {
	SendCommand(grpc.BidiStreamingServer[InputMessage, OutputMessage]) error
	mustEmbedUnimplementedWormholeServiceServer()
}

// UnimplementedWormholeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWormholeServiceServer struct{}

func (UnimplementedWormholeServiceServer) SendCommand(grpc.BidiStreamingServer[InputMessage, OutputMessage]) error {
	return status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedWormholeServiceServer) mustEmbedUnimplementedWormholeServiceServer() {}
func (UnimplementedWormholeServiceServer) testEmbeddedByValue()                         {}

// UnsafeWormholeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WormholeServiceServer will
// result in compilation errors.
type UnsafeWormholeServiceServer interface {
	mustEmbedUnimplementedWormholeServiceServer()
}

func RegisterWormholeServiceServer(s grpc.ServiceRegistrar, srv WormholeServiceServer) {
	// If the following call pancis, it indicates UnimplementedWormholeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WormholeService_ServiceDesc, srv)
}

func _WormholeService_SendCommand_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WormholeServiceServer).SendCommand(&grpc.GenericServerStream[InputMessage, OutputMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WormholeService_SendCommandServer = grpc.BidiStreamingServer[InputMessage, OutputMessage]

// WormholeService_ServiceDesc is the grpc.ServiceDesc for WormholeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WormholeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wormhole.WormholeService",
	HandlerType: (*WormholeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendCommand",
			Handler:       _WormholeService_SendCommand_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wormhole.proto",
}
