[package]
name = "polly"
version = "0.0.1"
authors = ["Amazon Firecracker team <firecracker-devel@amazon.com>"]
edition = "2021"

[dependencies]
ahash = "0.8.3"
libc = ">=0.2.39"
utils = { path="../utils" }
