package sysx

// kernel 6.11+
const PIDFD_GET_CGROUP_NAMESPACE = 0xff01
const PIDFD_GET_IPC_NAMESPACE = 0xff02
const PIDFD_GET_MNT_NAMESPACE = 0xff03
const PIDFD_GET_NET_NAMESPACE = 0xff04
const PIDFD_GET_PID_NAMESPACE = 0xff05
const PIDFD_GET_PID_FOR_CHILDREN_NAMESPACE = 0xff06
const PIDFD_GET_TIME_NAMESPACE = 0xff07
const PIDFD_GET_TIME_FOR_CHILDREN_NAMESPACE = 0xff08
const PIDFD_GET_USER_NAMESPACE = 0xff09
const PIDFD_GET_UTS_NAMESPACE = 0xff0a
const PIDFD_GET_INFO = 0xc040ff0b

// kernel 6.15+
const PIDFD_SELF = -10000
const PIDFD_SELF_PROCESS = -20000
