name: Check code formatting
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  treefmt:
    runs-on: macOS
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Install/update formatters
        run: brew install black treefmt swift-format clang-format rustup go
      - name: Install/update rustfmt
        run: |
          brew link --force rustup
          rustup default stable
          rustup update
      - name: Run treefmt
        run: treefmt --no-cache --fail-on-change -u debug -v
